### ISSUE TITLE
Game Version

### ISSUE THREAD

**Issue by MuthaX** [Sleepy93/DriverMP#2]
What version of the game (Driver) this client uses? Or where it can be downloaded?
I have only version (i don`t know its number) witch have glitch with invisible wheels (on win7).
I heard about patches for Driver but its everywhere deadlinks to that yet =\

Sorry if my english bad.

**Comment by Sleepy93** [comment]
The client support two version of Driver. 

> 1.2 US version.
> 6.3 EU version

I'll make a readme with other information :)

**Comment by Sleepy93** [comment]
For more information check readme.md
